"""Signed client for /ask, run inside the analytics container.

    python -m app.cli ask "Which students have not logged in for 14 days?" [--course-ids 2,3,4]
    python -m app.cli bench [--course-ids 2,3,4] [--markdown /tmp/benchmark.md]

bench asks the six talk questions word for word and then paraphrased.
"""

from __future__ import annotations

import argparse
import datetime as dt
import hashlib
import json
import os
import sys
import time
import urllib.error
import urllib.request
from pathlib import Path
from typing import Any

import duckdb

from app.ask import SIGNATURE_HEADER, TIMESTAMP_HEADER, sign
from app.config import DB_FILENAME
from app.db import READER_CONFIG
from app.demo_facts import DEMO_QUESTIONS, scope_names

API_URL = "http://127.0.0.1:8000/ask"
CLI_USER_REF = hashlib.sha256(b"app.cli").hexdigest()[:16]
BENCH_COURSES = [2, 3, 4]  # lmartinez: DA101, PROG101, STAT201
WARM_UP = "How many courses are there?"
MACHINE = "Apple M1 Pro, Docker Desktop 5 CPU / 7.67 GB, CPU only"


def post_ask(question: str, course_ids: list[int], max_rows: int | None = None, timeout: float = 900) -> tuple[int, dict]:
    secret = os.environ.get("ASKDATA_SHARED_SECRET", "")
    payload: dict[str, Any] = {"question": question, "course_ids": course_ids, "user_ref": CLI_USER_REF}
    if max_rows:
        payload["max_rows"] = max_rows
    body = json.dumps(payload).encode()
    ts = str(int(time.time()))
    request = urllib.request.Request(
        os.environ.get("ASK_URL", API_URL),
        data=body,
        method="POST",
        headers={"Content-Type": "application/json", TIMESTAMP_HEADER: ts, SIGNATURE_HEADER: sign(secret, ts, body)},
    )
    try:
        with urllib.request.urlopen(request, timeout=timeout) as response:
            return response.status, json.load(response)
    except urllib.error.HTTPError as err:
        try:
            return err.code, json.loads(err.read() or b"{}")
        except ValueError:
            return err.code, {"detail": {"reason": "http_error", "message": f"HTTP {err.code}"}}


def all_course_ids() -> list[int]:
    path = Path(os.environ.get("DATA_DIR", "/data")) / DB_FILENAME
    con = duckdb.connect(str(path), read_only=True, config=dict(READER_CONFIG))
    try:
        return [r[0] for r in con.execute("SELECT course_id FROM base.course ORDER BY course_id").fetchall()]
    finally:
        con.close()


def parse_ids(text: str | None) -> list[int]:
    if not text:
        return all_course_ids()
    return [int(part) for part in text.split(",") if part.strip()]


def _cell(value: Any, width: int = 40) -> str:
    text = "NULL" if value is None else str(value)
    return text if len(text) <= width else text[: width - 3] + "..."


def text_table(columns: list[str], rows: list[list[Any]], limit: int = 50) -> str:
    shown = [[_cell(v) for v in row] for row in rows[:limit]]
    widths = [max(len(c), *(len(r[i]) for r in shown)) if shown else len(c) for i, c in enumerate(columns)]
    line = lambda cells: " | ".join(c.ljust(w) for c, w in zip(cells, widths))  # noqa: E731
    out = [line(columns), "-+-".join("-" * w for w in widths), *(line(r) for r in shown)]
    if len(rows) > limit:
        out.append(f"... {len(rows) - limit} more rows")
    return "\n".join(out)


def cmd_ask(args: argparse.Namespace) -> int:
    course_ids = parse_ids(args.course_ids)
    status, body = post_ask(args.question, course_ids, args.max_rows)
    if status != 200:
        detail = body.get("detail", body)
        print(f"HTTP {status}", file=sys.stderr)
        print(json.dumps(detail, indent=2), file=sys.stderr)
        return 1
    print(body["sql"].strip())
    print()
    print(text_table(body["columns"], body["rows"]))
    print()
    timings = body.get("timings", {})
    print(
        f"{len(body['rows'])} rows{' (truncated)' if body.get('truncated') else ''}, "
        f"{body['elapsed_ms']:.0f} ms (model {timings.get('model_ms', 0):.0f} ms, sql {timings.get('sql_ms', 0):.0f} ms), "
        f"attempts {body['attempts']}, model {body['model']}, courses {course_ids}"
    )
    return 0


def _md_escape(text: str) -> str:
    return text.replace("|", "\\|")


def render_markdown(model: str, course_ids: list[int], results: list[dict[str, Any]], warm: dict[str, Any]) -> str:
    today = dt.date.today().isoformat()
    correct = sum(1 for r in results if r["correct"])
    lines = [
        "# Benchmark",
        "",
        f"Generated by `make bench` on {today}.",
        "",
        f"- Model: `{model}`",
        f"- Machine: {MACHINE}",
        f"- Scope: course_ids {course_ids} ({', '.join(scope_names(course_ids))}), as teacher lmartinez",
        f"- Warm-up call (model load and prompt cache): {warm['elapsed_ms']:.0f} ms",
        f"- Correct: {correct} of {len(results)}",
        "",
        "Each question runs once after the warm-up. The `exact` set uses the talk questions word for word; "
        "they are also few-shot examples in `analytics/examples.yaml`, so the model can copy the SQL. "
        "The `paraphrase` set asks the same thing in other words. `model ms` is the time spent waiting for "
        "Ollama (all attempts), split by Ollama into prompt evaluation and output generation (the rest is "
        "model loading and HTTP), `sql ms` is guard plus DuckDB. `correct` compares the rows with the facts in "
        "docs/demo-data.md (`app/demo_facts.py`).",
        "",
        "| # | Set | Question | Status | Elapsed ms | Model ms | Prompt ms | Output ms | SQL ms | Attempts | Rows | Correct |",
        "|---|---|---|---|---|---|---|---|---|---|---|---|",
    ]
    for i, r in enumerate(results, 1):
        lines.append(
            f"| {i} | {r.get('set', 'exact')} | {_md_escape(r['question'])} | {r['status']} | {r['elapsed_ms']:.0f} | "
            f"{r['model_ms']:.0f} | {r.get('prompt_ms', 0):.0f} | {r.get('output_ms', 0):.0f} | {r['sql_ms']:.0f} | "
            f"{r['attempts']} | {r['rows']} | {'yes' if r['correct'] else 'no'} |"
        )
    lines += ["", "## Generated SQL", ""]
    for i, r in enumerate(results, 1):
        lines += [f"### {i}. {r['question']} ({r.get('set', 'exact')})", ""]
        if r.get("error"):
            lines += [f"Error: `{r['error']}`", ""]
        if r.get("sql"):
            lines += ["```sql", r["sql"].strip(), "```", ""]
    lines += [
        "## Known limits",
        "",
        "- `/ask` returns data, not prose. Question 6 asks to explain the differences; the API answers "
        "with the numbers that support an explanation (completion rate, inactive share, biggest drop), "
        "and the explanation sentence belongs to the Moodle plugin UI or a later step.",
        "- Small models are not reliable SQL writers. The guard keeps wrong SQL from doing harm, but a "
        "query can be valid and still answer a different question; check the SQL shown with every answer.",
        "",
    ]
    return "\n".join(lines)


def cmd_bench(args: argparse.Namespace) -> int:
    course_ids = parse_ids(args.course_ids) if args.course_ids else BENCH_COURSES
    scope = scope_names(course_ids)
    status, warm = post_ask(WARM_UP, course_ids)
    warm_info = {"elapsed_ms": warm.get("elapsed_ms", 0.0) if status == 200 else 0.0}
    print(f"warm-up: HTTP {status}, {warm_info['elapsed_ms']:.0f} ms", file=sys.stderr)
    model = warm.get("model", os.environ.get("OLLAMA_MODEL", "?"))
    results = []
    runs = [("exact", d, d.question) for d in DEMO_QUESTIONS] + [("paraphrase", d, d.paraphrase) for d in DEMO_QUESTIONS]
    for kind, demo, question in runs:
        start = time.perf_counter()
        status, body = post_ask(question, course_ids)
        wall = (time.perf_counter() - start) * 1000.0
        if status == 200:
            timings = body.get("timings", {})
            calls = timings.get("calls", [])
            correct = demo.check(body["columns"], body["rows"], scope)
            row = {
                "status": 200,
                "elapsed_ms": body["elapsed_ms"],
                "model_ms": timings.get("model_ms", 0.0),
                "prompt_ms": sum(c.get("prompt_ms") or 0 for c in calls),
                "output_ms": sum(c.get("output_ms") or 0 for c in calls),
                "sql_ms": timings.get("sql_ms", 0.0),
                "attempts": body["attempts"],
                "rows": len(body["rows"]),
                "sql": body["sql"],
                "correct": correct,
            }
        else:
            detail = body.get("detail", {}) if isinstance(body.get("detail"), dict) else {}
            row = {
                "status": status,
                "elapsed_ms": wall,
                "model_ms": 0.0,
                "sql_ms": 0.0,
                "attempts": 2 if status == 422 else 0,
                "rows": 0,
                "sql": detail.get("sql", ""),
                "error": f"{detail.get('reason', status)}: {detail.get('message', '')}",
                "correct": False,
            }
        row["question"] = question
        row["set"] = kind
        results.append(row)
        print(f"{kind} {demo.example_id}: HTTP {status}, {row['elapsed_ms']:.0f} ms, correct={row['correct']}", file=sys.stderr)

    print(text_table(
        ["#", "set", "question", "status", "elapsed_ms", "model_ms", "prompt_ms", "output_ms", "sql_ms", "attempts", "rows", "correct"],
        [
            [i, r["set"], r["question"], r["status"], round(r["elapsed_ms"]), round(r["model_ms"]),
             round(r.get("prompt_ms", 0)), round(r.get("output_ms", 0)), round(r["sql_ms"]),
             r["attempts"], r["rows"], "yes" if r["correct"] else "no"]
            for i, r in enumerate(results, 1)
        ],
    ))
    if args.markdown:
        Path(args.markdown).write_text(render_markdown(model, course_ids, results, warm_info), encoding="utf-8")
    return 0


def main(argv: list[str]) -> int:
    parser = argparse.ArgumentParser(prog="python -m app.cli")
    sub = parser.add_subparsers(dest="command", required=True)
    p_ask = sub.add_parser("ask", help="ask one question")
    p_ask.add_argument("question")
    p_ask.add_argument("--course-ids", help="comma-separated ids; default: every course in the export")
    p_ask.add_argument("--max-rows", type=int)
    p_ask.set_defaults(func=cmd_ask)
    p_bench = sub.add_parser("bench", help="run the six demo questions")
    p_bench.add_argument("--course-ids", help=f"default: {','.join(map(str, BENCH_COURSES))}")
    p_bench.add_argument("--markdown", help="write a Markdown report to this path")
    p_bench.set_defaults(func=cmd_bench)
    args = parser.parse_args(argv)
    return args.func(args)


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
